---
- name: Configuracao novos servidores
  hosts: 67.205.140.39
  remote_user: pedro
  become: yes
  become_method: sudo

  tasks:
    - name: Atualizar pacotes
      apt:
        name: "*"
        state: latest

    - name: Instalar aptitude utilizando apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Instalar pacotes requeridos
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Atualizar apt e instalar docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Instalar docker modulo para o Python
      pip:
        name: docker
